# colors: supported values are 'b': blue, 'g': green, 'r': red, 'c': cyan, 'm': magenta, 'y': yellow, 'k': black, 'w': white
# linestyles: supported values are '-', '--', '-.', ':', 'None', ' ', '', 'solid', 'dashed', 'dashdot', 'dotted'
# https://matplotlib.org/stable/tutorials/introductory/customizing.html
report:
  collect_data: True
  input_directory: 03.02.2020
  output_directory: 03.02.2020/report
metrics:
  resource-total-size:
    metric_type: resource
    start_time: 01-01-2015
    end_time: 03-01-2021
    aggregation: 1M
    save_data: True
    series:
      - type: total
        label: Total Cumulative Resources
        color: b
        linestyle: '-'
    figure_configuration:
      type: line
      title: Cumulative Resource Size (Aggregated Monthly)
      caption: |
        The cumulative storage of all HydroShare resources plotted by the date in which the resource was created. These data are aggregated monthly and then summed cumulatively.
      rcParams:
        axes.titlesize: 24
        axes.labelsize: 16
        legend.fontsize: 16
        figure.figsize: 10, 6
      axis:
        xlabel: Date
        ylabel: Number of Users
        ylim: (0.0, None)
      figure:
        annotate: True
        grid: True
        legend: True

  users-active-30-day:
    metric_type: user
    start_time: 01-01-2015
    end_time: 03-01-2021
    active_range: 30
    step: 10
    save_data: True
    series:
      - type: active
        label: Active Users (30 days)
        color: b
        linestyle: '-'
      - type: total
        label: Total Users
        color: k
        linestyle: '-'
      - type: new
        label: New Users
        color: g
        linestyle: '-'
    figure_configuration:
      type: line
      title: Number of HydroShare User Accounts
      caption: |
        (1) Total cumulative HydroShare accounts through time based on the date each account was created, (2) active accounts are defined as those that have logged into HydroShare within the last 30 days, and (3) new accounts defined as those that were created within the active range (i.e. the portion of active users that created an account within the last 30 days).
      rcParams:
        #        font.size: 40.0
        axes.titlesize: 24
        axes.labelsize: 16
        legend.fontsize: 16
        figure.figsize: 10, 6
      axis:
        xlabel: Date
        ylabel: Number of Users
        ylim: (0.0, None)
      figure:
        annotate: True
        grid: True
        legend: True

  users-active-180-day:
    metric_type: user
    start_time: 01-01-2015
    end_time: 03-01-2021
    active_range: 180
    step: 10
    save_data: True
    series:
      - type: active
        label: Active Users (180 days)
        color: b
        linestyle: '-'
      - type: total
        label: Total Users
        color: k
        linestyle: '-'
      - type: new
        label: New Users
        color: g
        linestyle: '-'
    figure_configuration:
      type: line
      caption: |
        (1) Total cumulative HydroShare accounts through time based on the date each account is created, (2) active accounts defined as users that have logged into HydroShare within the last 180 days, and (3) new accounts defined as HydroShare accounts that were created within the active range (i.e. the portion of active users that created an account within the last 180 days).
      title: Number of HydroShare User Accounts
      rcParams:
        axes.titlesize: 24
        axes.labelsize: 16
        legend.fontsize: 16
        figure.figsize: 10, 6
      axis:
        xlabel: Date
        ylabel: Number of Users
        ylim: (0.0, None)
      figure:
        annotate: True
        grid: True
        legend: True

  users-all-180-day:
    metric_type: user
    start_time: 01-01-2015 
    end_time: 03-01-2021
    active_range: 180
    step: 10
    save_data: True
    series:
      - type: active
        label: Active Users (180 days)
        color: b
        linestyle: '-'
      - type: returning
        label: Returning Users
        color: r
        linestyle: '-'
      - type: new
        label: New Users
        color: g
        linestyle: '-'
    figure_configuration:
      type: line
      caption: |
        (1) Active accounts defined as users that have logged into HydroShare within the last 180 days, (2) new accounts defined as HydroShare accounts that were created within the active range (i.e. the portion of active users that created an account within the last 180 days), and (3) returning users defined as the portion of active users that created their account outside the active range.
      title: Total HydroShare Users Disaggregated
      rcParams:
        axes.titlesize: 24
        axes.labelsize: 16
        legend.fontsize: 16
        figure.figsize: 10, 6
      axis:
        xlabel: Date
        ylabel: Number of Users
        ylim: (0.0, None)
      figure:
        annotate: True
        grid: True
        legend: True



