report:
  collect_data: True
  input_directory: 03.02.2020
  output_directory: 03.02.2020/report
metrics:
  active-users-30-day:
    metric_type: user
    figure_name: users_all_30
    figure_caption: |
      (1) Total cumulative HydroShare accounts through time based on the date each account was created, (2) active accounts are defined as those that have logged into HydroShare within the last 30 days, and (3) new accounts defined as those that were created within the active range (i.e. the portion of active users that created an account within the last 30 days).
    start_time: 01-01-2015
    end_time: 03-01-2021
    active_range: 30
    step: 10
    series:
      # colors: supported values are 'b': blue, 'g': green, 'r': red, 'c': cyan, 'm': magenta, 'y': yellow, 'k': black, 'w': white
      # linestyles: supported values are '-', '--', '-.', ':', 'None', ' ', '', 'solid', 'dashed', 'dashdot', 'dotted'
      - type: active
        label: Active Users (30 days)
        color: b
        linestyle: '-'
      - type: total
        label: Total Users
        color: k
        linestyle: '-'
      - type: new
        label: New Users
        color: g
        linestyle: '-'
    figure_configuration:
      type: line
      rcParams:
        # https://matplotlib.org/stable/tutorials/introductory/customizing.html
        #        font.size: 40.0
        axes.titlesize: 24
        axes.labelsize: 16
        legend.fontsize: 16
        figure.figsize: 10, 6
      axis:
        xlabel: Date
        ylabel: Number of Users
        ylim: (0.0, None)
      figure:
        title: Number of HydroShare User Accounts
  active-users-180-day:
    metric_type: user
    figure_name: users_active_180
    figure_caption: |
      (1) Total cumulative HydroShare accounts through time based on the date each account is created, (2) active accounts defined as users that have logged into HydroShare within the last 180 days, and (3) new accounts defined as HydroShare accounts that were created within the active range (i.e. the portion of active users that created an account within the last 180 days).
    start_time: 01-01-2015
    end_time: 03-01-2021
    active_range: 180
    step: 10
    series:
      - type: active
        label: Active Users (180 days)
        color: b
        linestyle: '-'
      - type: total
        label: Total Users
        color: k
        linestyle: '-'
      - type: new
        label: New Users
        color: g
        linestyle: '-'
    figure_configuration:
      rcParams:
        axes.titlesize: 24
        axes.labelsize: 16
        legend.fontsize: 16
        figure.figsize: 10, 6
      axis:
        xlabel: Date
        ylabel: Number of Users
        ylim: (0.0, None)
      figure:
        title: Number of HydroShare User Accounts
  all-users-180-day:
    metric_type: user
    figure_name: users_all_180
    figure_caption: |
      (1) Active accounts defined as users that have logged into HydroShare within the last 180 days, (2) new accounts defined as HydroShare accounts that were created within the active range (i.e. the portion of active users that created an account within the last 180 days), and (3) returning users defined as the portion of active users that created their account outside the active range.
    start_time: 01-01-2015 
    end_time: 03-01-2021
    active_range: 180
    step: 10
    series:
      - type: active
        label: Active Users (180 days)
        color: b
        linestyle: '-'
      - type: returning
        label: Returning Users
        color: r
        linestyle: '-'
      - type: new
        label: New Users
        color: g
        linestyle: '-'
    figure_configuration:
      rcParams:
        axes.titlesize: 24
        axes.labelsize: 16
        legend.fontsize: 16
        figure.figsize: 10, 6
      axis:
        xlabel: Date
        ylabel: Number of Users
        ylim: (0.0, None)
      figure:
        title: Total HydroShare Users Disaggregated


